archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
    files:
      - LICENSE
      - README.md
builds:
  - id: linux-amd64
    binary: lmbc-linux-{{ .Arch }}
    main: ./
    goos:
      - linux
    goarch:
      - amd64
    #    ldflags:
    #      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
  - image_templates:
      - "vkumbhar94/lmbc:latest"
      - "vkumbhar94/lmbc:{{ .Tag }}"
      - "vkumbhar94/lmbc:v{{ .Major }}.{{ .Minor }}"
      - "vkumbhar94/lmbc:v{{ .Major }}"
    id: latest
    goos: linux
    goarch: amd64
    goarm: ""
    #    goamd64: "v2"
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.goreleaser
    # setting skip push to auto - auto does not push pre-release tags, only stable
    skip_push: "auto"